# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 684b364eb7f2aa03fbda8718181e5639c2e8886b98b1980685e3e7c84f0eb64f4c2cf7825fdf9086d8ea6b337d8bf4944727be6be3a40a2e7558564f6b7f151a

test:
  secret_key_base: 83c863b799c03bccedd81316c48d0b0363d1397d0de976a09afe19dc43889f0fb2f09f108d04de5f94d1155868e1faae68340edd5f7c8d354b2aed6a733d8d62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
